baseURL: "https://preciouscargokids.com/"
languageCode: en-us
title: Precious Cargo Kids
theme: PaperMod

# https://github.com/adityatelange/hugo-PaperMod/wiki/Installation
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/

# enableRobotsTXT: true

# minify:
#   disableXML: true
#   minifyOutput: true

params:
  author: Me
  ShowReadingTime: true
  ShowPostNavLinks: true